server:
  port: 10000

spring:
  application:
    name: @name@
  datasource:
    url: jdbc:mysql://localhost:3306/wechat_robot?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 459999
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      # Hibernate ddl auto
      #   create          Create the schemaand destory previous data
      #   validate        Validate the schema, make no changes to the databases
      #   create-drop     DisableDDL handling
      #   update           Update the schema if necessary
      ddl-auto: update
    # Show or not log for each sql query
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


# close auto catch error page
error:
  whitelabel:
    enabled: false


logging:
  config: classpath:logback-boot.xml
endpoints:
  health:
    sensitive: false

# document swagger config
swagger:
  name:  @name@
  desc: @description@
  version: @version@
  termsOfServiceUrl:
  basePackage: @groupId@
  contact:
    name: @description@
    url: @description@
    email: @description@

config:
  wechat:
    url: '10.211.55.4:2222'
schedule:
  cron: '*/5 * * * * *'
card:
  mode: true
  content: "<?xml version=\"1.0\"?><msg bigheadimgurl=\"%s\" smallheadimgurl=\"%s\" username=\"%s\" nickname=\"%s\" fullpy=\"aoliao\" shortpy=\"\" alias=\"19991203\" imagestatus=\"2\" scene=\"17\" province=\"中国\" city=\"中国\" sign=\"\" sex=\"1\" certflag=\"0\" certinfo=\"\" brandIconUrl=\"\" brandHomeUrl=\"\" brandSubscriptConfigUrl= \"\" brandFlags=\"0\" regionCode=\"CN_CN_CN\" />"
  bigheadimgurl: http://wx.qlogo.cn/mmhead/bNqVZcia7iaBwaJ4gVQv5ZVEO0hYvtXoTH0d2c529lUTg7kze1przwxg/0
  smallheadimgurl: http://wx.qlogo.cn/mmhead/bNqVZcia7iaBwaJ4gVQv5ZVEO0hYvtXoTH0d2c529lUTg7kze1przwxg/0
  # wxid
  username: wxid_w5qpig7dah8121
  # 昵称
  nickname: 天神下凡一锤五